{% set name = "morphospaces" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/morphospaces-{{ version }}.tar.gz
  sha256: 0b97246488c7cee41b8c869d65f9c06dd52728363c4181caf3b72528c3fd0aec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - h5py
    - magicgui
    - numpy
    - python >={{ python_min }}
    - pytorch-lightning
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - morphospaces
  commands:
    - pip list
    # - pip check  # pytorch-lightning requirements missmatch 
  requires:
    - napari
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/morphometrics/morphospaces
  summary: a library for creating  and exploring morphospaces.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
